from .AdminAuthPage import AdminAuthPage
from .AdminProductPage import AdminProductPage
from .AdminProductCart import AdminProductCart
from .AdminMainPage import AdminMainPageLocators
from .CategoryPage import CategoryPage
from .SearchResultPage import SearchResultPage
from .MainPage import MainPage
from .ProductPage import ProductPage
from .RegPage import RegPage
from .UserPC import UserPersonalCabinet
from .UserAuthPage import AuthPage
